from __future__ import annotations
from typing import Any, Dict, Protocol
class ExperimentRepositoryPort(Protocol):
    def save(self, payload: Dict[str, Any]) -> None: ...
    def get(self, experiment_id: str) -> Dict[str, Any] | None: ...
